version: '3'

services:
  # Banano Node service
  banano-node:
    image: bananocoin/banano:latest
    container_name: banano-node
    hostname: banano-node
    environment:
      - TERM=xterm
      - RPC_SECURE=1
      - WEBSOCKET_SECURE=1
      - RPC_SECURE_RPC_CERTIFICATE_PATH=/root/config/cert.pem
      - RPC_SECURE_RPC_KEY_PATH=/root/config/privkey.pem
      - RPC_SECURE_RPC_CHAIN_PATH=/root/config/chain.pem
    restart: unless-stopped
    ports:
      - "7071:7071"
      - "127.0.0.1:7072:7072"
    volumes:
      - ./banano-node:/root
      - ./config:/root/config

  # Banano Node Monitor service
  banano-node-monitor:
    image: nanotools/nanonodemonitor:latest
    container_name: banano-node-monitor
    hostname: banano-node-monitor
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=mydomain.com # Virtual host for Banano Node Monitor
      - LETSENCRYPT_HOST=mydomain.com # Domain for Let's Encrypt certificate
      - LETSENCRYPT_EMAIL=myemailaddress@mail.com # Email address for Let's Encrypt notifications
    volumes:
      - ./banano-node-monitor/config.php:/opt/nanoNodeMonitor/config.php # Mount custom config file

  # Nginx Reverse Proxy service
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DEFAULT_HOST=mydomain.com # Default host for Nginx Reverse Proxy
    volumes:
      - nginx-proxy-v1:/etc/nginx/vhost.d # Volume for Nginx Reverse Proxy configuration
      - nginx-proxy-v2:/usr/share/nginx/html # Volume for Nginx Reverse Proxy default HTML files
      - /var/run/docker.sock:/tmp/docker.sock:ro # Mount Docker socket for dynamic configuration
      - nginx-proxy-v3:/etc/nginx/certs # Volume for Nginx Reverse Proxy SSL certificates
    restart: always

  # LetsEncrypt Nginx Proxy Companion service
  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-letsencrypt
    restart: unless-stopped
    volumes:
      - nginx-proxy-v1:/etc/nginx/vhost.d # Volume for Nginx Reverse Proxy configuration
      - nginx-proxy-v2:/usr/share/nginx/html # Volume for Nginx Reverse Proxy default HTML files
      - /var/run/docker.sock:/var/run/docker.sock:ro # Mount Docker socket for dynamic configuration
      - nginx-proxy-v3:/etc/nginx/certs # Volume for Nginx Reverse Proxy SSL certificates
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy

  # Watchtower service
  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    restart: unless-stopped
    command: watchtower banano-node banano-node-monitor nginx-proxy letsencrypt-nginx-proxy-companion # Watchtower command to monitor and update containers
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Mount Docker socket for Watchtower to access containers

networks:
  banano-node-network:
    name: banano-node-network
    external: true

volumes:
  nginx-proxy-v1:
  nginx-proxy-v2:
  nginx-proxy-v3:
