version: '3'

services:
  banano-node:
    image: bananocoin/banano:latest
    container_name: banano-node
    hostname: banano-node
    environment:
      - TERM=xterm
    restart: unless-stopped
    ports:
      - "7071:7071"
      - "127.0.0.1:7072:7072"
    volumes:
      - ./banano-node:/root

  banano-node-monitor:
    image: nanotools/nanonodemonitor:latest
    container_name: banano-node-monitor
    hostname: banano-node-monitor
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=mydomain.com
      - LETSENCRYPT_HOST=mydomain.com
      - LETSENCRYPT_EMAIL=myemailaddress@mail.com
    volumes:
      - ./banano-node-monitor:/opt/nanoNodeMonitor

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DEFAULT_HOST=mydomain.com
    volumes:
      - nginx-proxy-v1:/etc/nginx/vhost.d
      - nginx-proxy-v2:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-proxy-v3:/etc/nginx/certs
    restart: always

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-letsencrypt
    restart: unless-stopped
    volumes:
      - nginx-proxy-v1:/etc/nginx/vhost.d
      - nginx-proxy-v2:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-proxy-v3:/etc/nginx/certs
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy

  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    restart: unless-stopped
    command: watchtower banano-node banano-node-monitor nginx-proxy letsencrypt-nginx-proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    external:
      name: banano-node-network

volumes:
  nginx-proxy-v1:
  nginx-proxy-v2:
  nginx-proxy-v3:
