version: "3"

services:
  banano-node:
    image: bananocoin/banano:latest
    container_name: banano-node
    hostname: banano-node
    environment:
      - TERM=xterm
    restart: unless-stopped
    ports:
      - "7071:7071"
      - "127.0.0.1:7072:7072"
      - "127.0.0.1:7074:7074"
    volumes:
      - ./banano-node:/root

  banano-node-monitor:
    image: nanotools/nanonodemonitor:latest
    container_name: banano-node-monitor
    hostname: banano-node-monitor
    restart: unless-stopped
    volumes:
      - ./banano-node-monitor:/opt/nanoNodeMonitor
    ports:
      - "80:80"

  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    restart: unless-stopped
    command: watchtower banano-node banano-node-monitor
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    external:
      name: banano-node-network
